---
# Post tasks

- name: Perform YUM package cleanup
  command: yum -y autoremove
  changed_when: no
  ignore_errors: yes

- meta: clear_host_errors
  when: ignore_unreachable is defined and ignore_unreachable
