- name: "SCORED | 5.1.1 | PATCH | Ensure cron daemon is enabled"
  systemd:
      name: crond
      enabled: yes
  when:
    - rhel7cis_level1 is defined and rhel7cis_level1
  tags:
      - level1
      - patch
      - rule_5.1.1

- name: "SCORED | 5.1.2 | PATCH | Ensure permissions on /etc/crontab are configured"
  file:
      dest: /etc/crontab
      owner: root
      group: root
      mode: 0600
  when:
    - rhel7cis_level1 is defined and rhel7cis_level1
  tags:
      - level1
      - patch
      - rule_5.1.2

- name: "SCORED | 5.1.3 | PATCH | Ensure permissions on /etc/cron.hourly are configured"
  file:
      dest: /etc/cron.hourly
      owner: root
      group: root
      mode: 0600
  when:
    - rhel7cis_level1 is defined and rhel7cis_level1
  tags:
    - level1
    - patch
    - rule_5.1.3

- name: "SCORED | 5.1.4 | PATCH | Ensure permissions on /etc/cron.daily are configured"
  file:
      dest: /etc/cron.daily
      owner: root
      group: root
      mode: 0600
  when:
    - rhel7cis_level1 is defined and rhel7cis_level1
  tags:
    - level1
    - patch
    - rule_5.1.4

- name: "SCORED | 5.1.5 | PATCH | Ensure permissions on /etc/cron.weekly are configured"
  file:
      dest: /etc/cron.weekly
      owner: root
      group: root
      mode: 0600
  when:
    - rhel7cis_level1 is defined and rhel7cis_level1
  tags:
    - level1
    - patch
    - rule_5.1.5

- name: "SCORED | 5.1.6 | PATCH | Ensure permissions on /etc/cron.monthly are configured"
  file:
      dest: /etc/cron.monthly
      owner: root
      group: root
      mode: 0600
  when:
    - rhel7cis_level1 is defined and rhel7cis_level1
  tags:
    - level1
    - patch
    - rule_5.1.6

- name: "SCORED | 5.1.7 | PATCH | Ensure permissions on /etc/cron.d are configured"
  file:
      dest: /etc/cron.d
      state: directory
      owner: root
      group: root
      mode: 0600
  when:
    - rhel7cis_level1 is defined and rhel7cis_level1
  tags:
    - level1
    - patch
    - rule_5.1.7

- name: "SCORED | 5.1.8 | PATCH | Ensure at/cron is restricted to authorized users"
  file:
      dest: /etc/at.deny
      state: absent
  when:
    - rhel7cis_level1 is defined and rhel7cis_level1
  tags:
    - level1
    - patch
    - rule_5.1.8

- name: "SCORED | 5.1.8 | PATCH | Ensure at/cron is restricted to authorized users"
  file:
      dest: /etc/at.allow
      state: touch
      owner: root
      group: root
      mode: 0600
  when:
    - rhel7cis_level1 is defined and rhel7cis_level1
  tags:
    - level1
    - patch
    - rule_5.1.8

- name: "SCORED | 5.1.8 | PATCH | Ensure at/cron is restricted to authorized users"
  file:
    dest: /etc/cron.deny
    state: absent
  when:
    - rhel7cis_level1 is defined and rhel7cis_level1
  tags:
    - level1
    - patch
    - rule_5.1.8

- name: "SCORED | 5.1.8 | PATCH | Ensure at/cron is restricted to authorized users"
  file:
    dest: /etc/cron.allow
    state: touch
    owner: root
    group: root
    mode: 0600
  when:
    - rhel7cis_level1 is defined and rhel7cis_level1
  tags:
    - level1
    - patch
    - rule_5.1.8

- name: "SCORED | 5.2.1 | PATCH | Ensure permissions on /etc/ssh/sshd_config are configured"
  file:
    dest: /etc/ssh/sshd_config
    state: file
    owner: root
    group: root
    mode: 0600
  when:
    - rhel7cis_level1 is defined and rhel7cis_level1
  tags:
    - level1
    - patch
    - rule_5.2.1

- name: "SCORED | 5.2.2 | PATCH | Ensure SSH Protocol is set to 2"
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: '^Protocol'
    line: 'Protocol 2'
  when:
    - rhel7cis_level1 is defined and rhel7cis_level1
  tags:
    - level1
    - patch
    - rule_5.2.2

- name: "SCORED | 5.2.3 | PATCH | Ensure SSH LogLevel is set to INFO"
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: '^LogLevel'
    line: 'LogLevel INFO'
  when:
    - rhel7cis_level1 is defined and rhel7cis_level1
  tags:
    - level1
    - patch
    - rule_5.2.3

- name: "SCORED | 5.2.4 | PATCH | Ensure SSH X11 forwarding is disabled"
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: '^X11Forwarding'
    line: 'X11Forwarding no'
  when:
    - rhel7cis_level1 is defined and rhel7cis_level1
  tags:
    - level1
    - patch
    - rule_5.2.4

- name: "SCORED | 5.2.5 | PATCH | Ensure SSH MaxAuthTries is set to 4 or less"
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: '^(#)?MaxAuthTries \d'
    line: 'MaxAuthTries 4'
  when:
    - rhel7cis_level1 is defined and rhel7cis_level1
  tags:
    - level1
    - patch
    - rule_5.2.5

- name: "SCORED | 5.2.6 | PATCH | Ensure SSH IgnoreRhosts is enabled"
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: '^IgnoreRhosts'
    line: 'IgnoreRhosts yes'
  when:
    - rhel7cis_level1 is defined and rhel7cis_level1
  tags:
    - level1
    - patch
    - rule_5.2.6

- name: "SCORED | 5.2.7 | PATCH | Ensure SSH HostbasedAuthentication is disabled"
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: '^HostbasedAuthentication'
    line: 'HostbasedAuthentication no'
  when:
    - rhel7cis_level1 is defined and rhel7cis_level1
  tags:
    - level1
    - patch
    - rule_5.2.7

- name: "SCORED | 5.2.8 | PATCH | Ensure SSH root login is disabled"
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: 'PermitRootLogin no'
  when:
    - rhel7cis_permit_ssh_root_login_disabled is defined and rhel7cis_permit_ssh_root_login_disabled
  tags:
    - level1
    - patch
    - rule_5.2.8

- name: "SCORED | 5.2.9 | PATCH | Ensure SSH PermitEmptyPasswords is disabled"
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: '^PermitEmptyPasswords'
    line: 'PermitEmptyPasswords no'
  when:
    - rhel7cis_level1 is defined and rhel7cis_level1
  tags:
    - level1
    - patch
    - rule_5.2.9

- name: "SCORED | 5.2.10 | PATCH | Ensure SSH PermitUserEnvironment is disabled"
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: '^PermitUserEnvironment'
    line: 'PermitUserEnvironment no'
  when:
    - rhel7cis_level1 is defined and rhel7cis_level1
  tags:
    - level1
    - patch
    - rule_5.2.10

# Removed 5.2.11 from CIS Benchmark
# - name: "SCORED | 5.2.11 | PATCH | Ensure only approved ciphers are used"
#   lineinfile:
#       state: present
#       dest: /etc/ssh/sshd_config
#       regexp: '^Ciphers'
#       line: 'Ciphers aes128-ctr,aes192-ctr,aes256-ctr'
#   tags:
#       - level1
#       - level2
#       - patch
#       - rule_5.2.11

- name: "SCORED | 5.2.11 | PATCH | Ensure only approved MAC algorithms are used"
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: '^MACs'
    line: 'MACs {{ rhel7cis_ssh_mac_algorithms | quote }}'
    #line: 'MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com'
  when:
    - rhel7cis_level1 is defined and rhel7cis_level1
    - rhel7cis_ssh_mac_algorithms is defined
  tags:
    - level1
    - patch
    - rule_5.2.11

- name: "SCORED | 5.2.12 | PATCH | Ensure SSH Idle Timeout Interval is configured"
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: '^ClientAliveInterval'
    line: 'ClientAliveInterval 300'
  when:
    - rhel7cis_level1 is defined and rhel7cis_level1
  tags:
    - level1
    - patch
    - rule_5.2.12

- name: "SCORED | 5.2.14 | PATCH | Ensure SSH LoginGraceTime is set to one minute or less"
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: '^LoginGraceTime'
    line: 'LoginGraceTime 60'
  when:
    - rhel7cis_level1 is defined and rhel7cis_level1
  tags:
    - level1
    - patch
    - rule_5.2.13

- name: "SCORED | 5.2.15 | PATCH | Ensure SSH access is limited"
  command: /bin/true
  changed_when: no
  when:
    - rhel7cis_level1 is defined and rhel7cis_level1
  tags:
    - level1
      - patch
      - rule_5.2.14

- name: "SCORED | 5.2.15 | PATCH | Ensure SSH warning banner is configured"
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: '^Banner'
    line: 'Banner /etc/issue'
  when:
    - rhel7cis_level1 is defined and rhel7cis_level1
  tags:
    - level1
    - patch
    - rule_5.2.15

- name: "SCORED | 5.3.1 | PATCH | Ensure password creation requirements are configured"
  lineinfile:
    state: present
    dest: /etc/security/pwquality.conf
    regexp: '^{{ item.key }}'
    line: '{{ item.key }} = {{ item.value }}'
  with_items:
    - { key: 'minlen',  value: '14' }
    - { key: 'dcredit', value: '-1' }
    - { key: 'ucredit', value: '-1' }
    - { key: 'ocredit', value: '-1' }
    - { key: 'lcredit', value: '-1' }
  when:
    - rhel7cis_level1 is defined and rhel7cis_level1
    - rhel7cis_password_creation_requirements is defined and rhel7cis_password_creation_requirements 
  tags:
    - level1
    - patch
    - rule_5.3.1

- name: "SCORED | 5.3.2 | Ensure lockout for failed password attempts is configured | system-auth"
  pamd:
    name: system-auth
    type: auth
    control: required
    module_path: pam_faillock.so
    module_arguments: 'preauth
        audit
        silent
        deny=5
        unlock_time=900'
    state: updated
  ignore_errors: yes
  when:
    - rhel7cis_level1 is defined and rhel7cis_level1
  tags:
    - level1
    - patch
    - rule_5.3.2
    - low

- name: "SCORED | 5.3.2 | Ensure lockout for failed password attempts is configured | system-auth"
  pamd:
    name: system-auth
    type: auth
    control: '[success=1 default=bad]'
    module_path: pam_unix.so
    state: updated
  ignore_errors: yes
  when:
    - rhel7cis_level1 is defined and rhel7cis_level1
  tags:
    - level1
    - patch
    - rule_5.3.2
    - low

- name: "SCORED | 5.3.2 | Ensure lockout for failed password attempts is configured | system-auth"
  pamd:
    name: system-auth
    type: auth
    control: '[default=die]'
    module_path: pam_faillock.so
    module_arguments: 'authfail
        audit
        deny=5
        unlock_time=900'
    state: updated
  ignore_errors: yes
  when:
    - rhel7cis_level1 is defined and rhel7cis_level1
  tags:
    - level1
    - patch
    - rule_5.3.2
    - low

- name: "SCORED | 5.3.2 | Ensure lockout for failed password attempts is configured | system-auth"
  pamd:
    name: system-auth
    type: auth
    control: sufficient
    module_path: pam_faillock.so
    module_arguments: 'authsucc
        audit
        deny=5
        unlock_time=900'
    state: updated
  ignore_errors: yes
  when:
    - rhel7cis_level1 is defined and rhel7cis_level1
  tags:
    - level1
    - patch
    - rule_5.3.2
    - low

- name: "SCORED | 5.3.2 | Ensure lockout for failed password attempts is configured | password-auth"
  pamd:
    name: password-auth
    type: auth
    control: required
    module_path: pam_faillock.so
    module_arguments: 'preauth
        audit
        silent
        deny=5
        unlock_time=900'
    state: updated
  ignore_errors: yes
  when:
    - rhel7cis_level1 is defined and rhel7cis_level1
  tags:
    - level1
    - patch
    - rule_5.3.2
    - low

- name: "SCORED | 5.3.2 | Ensure lockout for failed password attempts is configured | password-auth"
  pamd:
    name: password-auth
    type: auth
    control: '[success=1 default=bad]'
    module_path: pam_unix.so
    state: updated
  ignore_errors: yes
  when:
    - rhel7cis_level1 is defined and rhel7cis_level1
  tags:
    - level1
    - patch
    - rule_5.3.2
    - low

- name: "SCORED | 5.3.2 | Ensure lockout for failed password attempts is configured | password-auth"
  pamd:
    name: password-auth
    type: auth
    control: '[default=die]'
    module_path: pam_faillock.so
    module_arguments: 'authfail
        audit
        deny=5
        unlock_time=900'
    state: updated
  ignore_errors: yes
  when:
    - rhel7cis_level1 is defined and rhel7cis_level1
  tags:
    - level1
    - patch
    - rule_5.3.2
    - low

- name: "SCORED | 5.3.2 | Ensure lockout for failed password attempts is configured | password-auth"
  pamd:
    name: password-auth
    type: auth
    control: sufficient
    module_path: pam_faillock.so
    module_arguments: 'authsucc
        audit
        deny=5
        unlock_time=900'
    state: updated
  ignore_errors: yes
  when:
    - rhel7cis_level1 is defined and rhel7cis_level1
  tags:
    - level1
    - patch
    - rule_5.3.2
    - low

- name: "SCORED | 5.3.3 | Ensure password reuse is limited | password-auth"
  pamd:
    name: password-auth
    type: password
    control: sufficient
    module_path: pam_pwhistory.so
    module_arguments: 'remember=5'
    state: updated
  ignore_errors: yes
  when:
    - rhel7cis_level1 is defined and rhel7cis_level1
  tags:
    - level1
    - patch
    - rule_5.3.3
    - low

- name: "SCORED | 5.3.3 | Ensure password reuse is limited | system-auth"
  pamd:
    name: system-auth
    type: password
    control: sufficient
    module_path: pam_pwhistory.so
    module_arguments: 'remember=5'
    state: updated
  ignore_errors: yes
  when:
    - rhel7cis_level1 is defined and rhel7cis_level1
  tags:
    - level1
    - patch
    - rule_5.3.3
    - low

- name: "SCORED | 5.3.4 | PATCH | Ensure password hashing algorithm is SHA-512"
  command: authconfig --passalgo=sha512 --update
  when:
    - rhel7cis_level1 is defined and rhel7cis_level1
  tags:
    - level1
    - patch
    - rule_5.3.4

- name: "SCORED | 5.4.1.1 | PATCH | Ensure password expiration is 365 days or less"
  lineinfile:
      state: present
      dest: /etc/login.defs
      regexp: '^PASS_MAX_DAYS'
      line: 'PASS_MAX_DAYS 90'
  when:
    - rhel7cis_level1 is defined and rhel7cis_level1
    - rhel7cis_password_expiration is defined and rhel7cis_password_expiration
  tags:
    - level1
    - patch
    - rule_5.4.1.1

- name: "SCORED | 5.4.1.2 | PATCH | Ensure minimum days between password changes is 7 or more"
  lineinfile:
      state: present
      dest: /etc/login.defs
      regexp: '^PASS_MIN_DAYS'
      line: 'PASS_MIN_DAYS 7'
  when:
    - rhel7cis_level1 is defined and rhel7cis_level1
    - rhel7cis_password_minimum_days_password_change is defined and rhel7cis_password_minimum_days_password_change
  tags:
    - level1
    - patch
    - rule_5.4.1.2

- name: "SCORED | 5.4.1.3 | PATCH | Ensure password expiration warning days is 7 or more"
  lineinfile:
    state: present
    dest: /etc/login.defs
    regexp: '^PASS_WARN_AGE'
    line: 'PASS_WARN_AGE 7'
  when:
    - rhel7cis_level1 is defined and rhel7cis_level1
  tags:
    - level1
    - patch
    - rule_5.4.1.3

- name: "SCORED | 5.4.1.4 | PATCH | Ensure inactive password lock is 30 days or less"
  command: useradd -D -f 30
  when:
    - rhel7cis_level1 is defined and rhel7cis_level1
  tags:
    - level1
    - patch
    - rule_5.4.1.4
    - low

- name: "SCORED | 5.4.1.5 | Ensure all users last password change date is in the past (Scored)"
  debug:
    msg: 'Confirm all password change dates are in the past.'
  when:
    - rhel7cis_level1 is defined and rhel7cis_level1
  tags:
    - level1
    - patch
    - rule_5.4.1.5
    - low

- name: "SCORED | 5.4.2 | PATCH | Ensure system accounts are non-login"
  copy:
    src: scripts/five_four_two.sh
    dest: /opt/five_four_two.sh
    owner: root
    group: root
    mode: 0700
  when:
    - rhel7cis_level1 is defined and rhel7cis_level1
    - rhel7cis_ensure_system_accounts_are_non_login is defined and rhel7cis_ensure_system_accounts_are_non_login
  tags:
    - level1
    - patch
    - rule_5.4.2
    - low

- name: "SCORED | 5.4.2 | PATCH | Ensure system accounts are non-login"
  shell: /opt/five_four_two.sh
  args:
    executable: /bin/bash
  when:
    - rhel7cis_level1 is defined and rhel7cis_level1
    - rhel7cis_ensure_system_accounts_are_non_login is defined and rhel7cis_ensure_system_accounts_are_non_login
  tags:
    - level1
    - patch
    - rule_5.4.2
    - low

- name: "SCORED | 5.4.2 | PATCH | Ensure system accounts are non-login"
  copy:
    src: scripts/five_four_two.sh
    dest: /opt/five_four_two.sh
    owner: root
    group: root
    state: absent
  when:
    - rhel7cis_level1 is defined and rhel7cis_level1
    - rhel7cis_ensure_system_accounts_are_non_login is defined and rhel7cis_ensure_system_accounts_are_non_login
  tags:
    - level1
    - patch
    - rule_5.4.2
    - low

- name: "SCORED | 5.4.3 | PATCH | Ensure default group for the root account is GID 0"
  command: usermod -g 0 root
  when:
    - rhel7cis_level1 is defined and rhel7cis_level1
  tags:
    - level1
    - patch
    - rule_5.4.3

- name: "SCORED | 5.4.4 | PATCH | Ensure default user umask is 027 or more restrictive"
  lineinfile:
    state: present
    dest: /etc/bashrc
    regexp: 'umask'
    line: 'umask {{ rhel7cis_default_user_umask }}'
  when:
    - rhel7cis_level1 is defined and rhel7cis_level1
    - rhel7cis_modify_default_user_umask is defined and rhel7cis_modify_default_user_umask
  tags:
    - level1
    - patch
    - rule_5.4.4
    - low

- name: "SCORED | 5.4.4 | PATCH | Ensure default user umask is 027 or more restrictive"
  lineinfile:
      state: present
      dest: /etc/profile
      regexp: 'umask'
      line: 'umask {{ rhel7cis_default_user_umask }}'
  when:
    - rhel7cis_level1 is defined and rhel7cis_level1
    - rhel7cis_modify_default_user_umask is defined and rhel7cis_modify_default_user_umask
  tags:
    - level1
    - patch
    - rule_5.4.4
    - low

- name: "SCORED | 5.4.4 | PATCH | Ensure default user umask is 027 or more restrictive"
  find:
    paths: /etc/profile.d/
    recurse: yes
    patterns: "*.sh"
  register: profiled_dir
  when:
    - rhel7cis_level1 is defined and rhel7cis_level1
    - rhel7cis_modify_default_user_umask is defined and rhel7cis_modify_default_user_umask
  tags:
    - level1
    - patch
    - rule_5.4.4
    - low

- name: "SCORED | 5.4.4 | PATCH | Ensure default user umask is 027 or more restrictive"
  lineinfile:
    state: present
    dest: "{{ item }}"
    regexp: 'umask'
    line: 'umask {{ rhel7cis_default_user_umask }}'
    backup: yes
  with_items: profiled_dir.files.path
  ignore_errors: yes
  when:
    - rhel7cis_level1 is defined and rhel7cis_level1
    - rhel7cis_modify_default_user_umask is defined and rhel7cis_modify_default_user_umask
  tags:
    - level1
    - patch
    - rule_5.4.4
    - low

- name: "SCORED | 5.4.5 | PATCH | Ensure default user shell timeout is 900 seconds or less"
  lineinfile:
    state: present
    dest: /etc/bashrc
    regexp: '^TMOUT'
    line: 'TMOUT=600'
  when:
    - rhel7cis_level2 is defined and rhel7cis_level2
  tags:
    - level2
    - patch
    - rule_5.4.5
    - low

- name: "SCORED | 5.4.5 | PATCH | Ensure default user shell timeout is 900 seconds or less"
  lineinfile:
    state: present
    dest: /etc/profile
    regexp: '^TMOUT'
    line: 'TMOUT=600'
  when:
    - rhel7cis_level2 is defined and rhel7cis_level2
  tags:
    - level2
    - patch
    - rule_5.4.5
    - low

- name: "NOTSCORED | 5.5 | PATCH | Ensure root login is restricted to system console"
  command: /bin/true
  changed_when: no
  when:
    - rhel7cis_level1 is defined and rhel7cis_level1
  tags:
    - level1
    - patch
    - rule_5.5

- name: "SCORED | 5.6 | PATCH | Ensure access to the su command is restricted"
  lineinfile:
    state: present
    dest: /etc/pam.d/su
    regexp: '^#auth\s+required\s+pam_wheel\.so'
    line: 'auth           required        pam_wheel.so use_uid'
  when:
    - rhel7cis_level1 is defined and rhel7cis_level1
  tags:
    - level1
    - patch
    - rule_5.6
